### ISSUE TITLE
Crossfeed DNS Configuration

### ISSUE THREAD

**Issue by hillaryj** [cisagov/cool-dns-cyber.dhs.gov#17]
# To do

- [ ] Terraform the CNAME entries added by hand for crossfeed
- [ ] Follow up with Crossfeed team to get any other changes they need

**Comment by hillaryj** [comment]
@cisagov/esi-interns

**Comment by cablej** [comment]
Here's the DNS records that can be added:

`staging.crossfeed.cyber.dhs.gov` `CNAME` `d179mq0xxrmh9p.cloudfront.net`

`api.staging.crossfeed.cyber.dhs.gov` `CNAME` `doshtdnix22dp.cloudfront.net`
