### ISSUE TITLE
Resource cannot be applied

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cool-dns-cyber.dhs.gov#79]
# 🐛 Summary #

The resource [`aws_acm_certificate.rules`](https://github.com/cisagov/cool-dns-cyber.dhs.gov/blob/9a8895c88439c1057660e6c8bcaf4ca976c37875/acm_rules_vm.tf#L5-L18) cannot be applied.

## To reproduce ##

Try to run `terraform apply`.  Watch the above resource fail to apply with the following error:
```
╷
│ Error: Error describing created certificate: Expected certificate to be issued but was in state EXPIRED
│
│   with aws_acm_certificate_validation.rules,
│   on acm_rules_vm.tf line 49, in resource "aws_acm_certificate_validation" "rules":
│   49: resource "aws_acm_certificate_validation" "rules" {
│
╵
```

## Expected behavior ##

I would expect a clean `terraform apply`.

**Comment by dav3r** [comment]
I manually deleted the expired certificate via the AWS Certificate Manager web console, then I re-ran the `terraform apply` for this repo, which successfully created a fresh certificate and related DNS record.  A subsequent `terraform apply` ran cleanly and without any further changes.

**Comment by jsf9k** [comment]
Thank you for spending some time on this!

**Comment by dav3r** [comment]
No problem- it finally got in my way as I was working on https://github.com/cisagov/publish-egress-ip-terraform/pull/6.
